/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ExamCell;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import test.MySQLConnection;
//import static Examcell.GetStudDeails.adaceminid;
//import static Examcell.GetStudDeails.mobileno;

/**
 *
 * @author Asus
 */
public class E_updatestud extends javax.swing.JFrame {

    /**
     * Creates new form E_updatestud
     */
    public E_updatestud() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    public static String StudEnrollID;

    public static void setOldValues(String ENROLLMENTID) {
        E_updatestud.StudEnrollID = ENROLLMENTID;
        EnrollmentId.setText(ENROLLMENTID);

        GetStudDeails obj = new GetStudDeails();
        obj.getDataStud(ENROLLMENTID);
        
        FullName.setText(obj.fullname);
        Password.setText(obj.password);
        ContactNumber.setText(obj.mobileno.toString());
        EmailId.setText(obj.email);
        Dob.setDate(obj.dob);
        
       
        
        
        DeptSec.setSelectedItem(obj.DeptCode);
        MotherName.setText(obj.mothername );
        FatherName.setText(obj.fatherrname );
        YearOfAdmission.setText(obj.yoa);
        State.setSelectedItem(obj.state );
        ClassSec.setSelectedItem(obj.studclass );
        City.setText(obj.city );
        Address.setText(obj.address);
        
        AcadmicYear.setText("");
        
        
        
                
    }
    
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        EnrollmentId = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        ContactNumber = new javax.swing.JTextField();
        EmailId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Dob = new com.toedter.calendar.JDateChooser();
        DeptSec = new javax.swing.JComboBox<>();
        MotherName = new javax.swing.JTextField();
        FatherName = new javax.swing.JTextField();
        State = new javax.swing.JComboBox<>();
        City = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Address = new javax.swing.JTextArea();
        FullName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Updatestudentbtn = new javax.swing.JButton();
        Gender = new javax.swing.JComboBox<>();
        AcadmicYear = new javax.swing.JTextField();
        YearOfAdmission = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        ClassSec = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(780, 750));

        jPanel3.setBackground(new java.awt.Color(19, 103, 149));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setPreferredSize(new java.awt.Dimension(780, 700));

        EnrollmentId.setBackground(new java.awt.Color(250, 250, 250));
        EnrollmentId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EnrollmentId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnrollmentIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EnrollmentIdFocusLost(evt);
            }
        });
        EnrollmentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrollmentIdActionPerformed(evt);
            }
        });

        Password.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFocusLost(evt);
            }
        });
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });

        ContactNumber.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ContactNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ContactNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ContactNumberFocusLost(evt);
            }
        });
        ContactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactNumberActionPerformed(evt);
            }
        });

        EmailId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EmailId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmailIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailIdFocusLost(evt);
            }
        });
        EmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailIdActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(250, 250, 250));
        jLabel2.setText("Date Of Birth :");

        Dob.setForeground(new java.awt.Color(250, 250, 250));

        DeptSec.setBackground(new java.awt.Color(250, 250, 250));
        DeptSec.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DeptSec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSE", "IT", "ENTC", "CIVIL", "ELN", "MECH", "MTECH" }));
        DeptSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeptSecActionPerformed(evt);
            }
        });

        MotherName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        MotherName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MotherNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MotherNameFocusLost(evt);
            }
        });
        MotherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotherNameActionPerformed(evt);
            }
        });

        FatherName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        FatherName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FatherNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FatherNameFocusLost(evt);
            }
        });
        FatherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FatherNameActionPerformed(evt);
            }
        });

        State.setBackground(new java.awt.Color(250, 250, 250));
        State.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        State.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Andhra Pradesh", "Assam", "Arunachal Pradesh", "Bihar", "Goa", "Gujarat", "Jammu and Kashmir", "Jharkhand", "West Bengal", "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Orissa", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Tripura", "Uttaranchal", "Uttar Pradesh", "Haryana", "Himachal Pradesh", "Chhattisgarh" }));

        City.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        City.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CityFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(250, 250, 250));
        jLabel3.setText("Acadmic Year:");

        Address.setColumns(20);
        Address.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Address.setRows(2);
        jScrollPane1.setViewportView(Address);

        FullName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FullName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FullNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FullNameFocusLost(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 250, 250));
        jLabel1.setText("Name:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(250, 250, 250));
        jLabel6.setText("Enrollment Id:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(250, 250, 250));
        jLabel7.setText("Gender:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(250, 250, 250));
        jLabel8.setText("Password:");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(250, 250, 250));
        jLabel9.setText("Contact No. :");

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(250, 250, 250));
        jLabel10.setText("Email Id:");

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(250, 250, 250));
        jLabel11.setText("Department:");

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(250, 250, 250));
        jLabel12.setText("Year of Admission:");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(250, 250, 250));
        jLabel13.setText("Mother's Name:");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(250, 250, 250));
        jLabel14.setText("Father's Name:");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(250, 250, 250));
        jLabel16.setText("City:");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(250, 250, 250));
        jLabel17.setText("Address:");

        Updatestudentbtn.setBackground(new java.awt.Color(19, 103, 149));
        Updatestudentbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Updatestudentbtn.setForeground(new java.awt.Color(250, 250, 250));
        Updatestudentbtn.setText("Update");
        Updatestudentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatestudentbtnActionPerformed(evt);
            }
        });

        Gender.setBackground(new java.awt.Color(250, 250, 250));
        Gender.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderActionPerformed(evt);
            }
        });

        AcadmicYear.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        AcadmicYear.setForeground(new java.awt.Color(250, 250, 250));

        YearOfAdmission.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        YearOfAdmission.setForeground(new java.awt.Color(250, 250, 250));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(250, 250, 250));
        jLabel18.setText("State:");

        ClassSec.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ClassSec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FY-01", "FY-02", "SY-03", "SY-04", "TY-05", "TY-06", "BE-07", "BE-08" }));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(250, 250, 250));
        jLabel5.setText("Class:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(250, 250, 250));
        jLabel4.setText("Update Student");

        jLabel15.setBackground(new java.awt.Color(204, 255, 255));
        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(250, 250, 250));
        jLabel15.setText("Photo");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(250, 250, 250));
        jLabel19.setText("Path");
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jButton1.setBackground(new java.awt.Color(19, 103, 149));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(250, 250, 250));
        jButton1.setText("Edit Photo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(250, 250, 250));
        jLabel21.setText("Name");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(302, 302, 302)
                        .addComponent(Updatestudentbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 251, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(FatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(38, 38, 38)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DeptSec, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MotherName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(YearOfAdmission, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(State, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ClassSec, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(AcadmicYear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Dob, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EnrollmentId, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(ContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(DeptSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(MotherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(FatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(EnrollmentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(YearOfAdmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(ClassSec, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(AcadmicYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(114, 114, 114)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(State, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel19))
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Updatestudentbtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 627, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EnrollmentIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EnrollmentIdFocusGained
        // TODO add your handling code here:
        if (EnrollmentId.getText().equals("EnrollmentId")) {
            EnrollmentId.setText("");
            EnrollmentId.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_EnrollmentIdFocusGained

    private void EnrollmentIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EnrollmentIdFocusLost
        // TODO add your handling code here:
        if (EnrollmentId.getText().equals("")) {
            EnrollmentId.setText("EnrollmentId");
            EnrollmentId.setForeground(new Color(153, 153, 153));
        }

    }//GEN-LAST:event_EnrollmentIdFocusLost

    private void EnrollmentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrollmentIdActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_EnrollmentIdActionPerformed

    private void PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusGained
        // TODO add your handling code here:
        if (Password.getText().equals("Password")) {
            Password.setText("");
            Password.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_PasswordFocusGained

    private void PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusLost
        // TODO add your handling code here:
        if (Password.getText().equals("")) {
            Password.setText("Password");
            Password.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_PasswordFocusLost

    private void ContactNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContactNumberFocusGained
        // TODO add your handling code here:
        if (ContactNumber.getText().equals("Contact Number")) {
            ContactNumber.setText("");
            ContactNumber.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_ContactNumberFocusGained

    private void ContactNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContactNumberFocusLost
        // TODO add your handling code here:
        if (ContactNumber.getText().equals("")) {
            ContactNumber.setText("Contact Number");
            ContactNumber.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_ContactNumberFocusLost

    private void ContactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactNumberActionPerformed

    private void GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderActionPerformed

    private void EmailIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailIdFocusGained
        // TODO add your handling code here:
        if (EmailId.getText().equals("Email Id")) {
            EmailId.setText("");
            EmailId.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_EmailIdFocusGained

    private void EmailIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailIdFocusLost
        // TODO add your handling code here:
        if (EmailId.getText().equals("")) {
            EmailId.setText("Email Id");
            EmailId.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_EmailIdFocusLost

    private void EmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailIdActionPerformed

    private void DeptSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeptSecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeptSecActionPerformed

    private void MotherNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MotherNameFocusGained
        // TODO add your handling code here:
        if (MotherName.getText().equals("Mother Name")) {
            MotherName.setText("");
            MotherName.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_MotherNameFocusGained

    private void MotherNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MotherNameFocusLost
        // TODO add your handling code here:
        if (MotherName.getText().equals("")) {
            MotherName.setText("Mother Name");
            MotherName.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_MotherNameFocusLost

    private void FatherNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FatherNameFocusGained
        // TODO add your handling code here:
        if (FatherName.getText().equals("Father Name")) {
            FatherName.setText("");
            FatherName.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_FatherNameFocusGained

    private void FatherNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FatherNameFocusLost
        // TODO add your handling code here:
        if (FatherName.getText().equals("")) {
            FatherName.setText("Father Name");
            FatherName.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_FatherNameFocusLost

    private void FatherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FatherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FatherNameActionPerformed

    private void CityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CityFocusGained
        // TODO add your handling code here:
        if (City.getText().equals("City")) {
            City.setText("");
            City.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_CityFocusGained

    private void CityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CityFocusLost
        // TODO add your handling code here:
        if (City.getText().equals("")) {
            City.setText("City");
            City.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_CityFocusLost

    private void UpdatestudentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatestudentbtnActionPerformed
        // TODO add your handling code here:
        try {

            Connection myConn = MySQLConnection.getConnection();

            String enrollmentId1 = EnrollmentId.getText();
            String password1 = Password.getText();
            String fullName1 = FullName.getText();

            String contactNumber1 = ContactNumber.getText();
            String emailId1 = EmailId.getText();
            String motherName1 = MotherName.getText();
            String fatherName1 = FatherName.getText();
            String city1 = City.getText();
            String gender1 = Gender.getSelectedItem().toString();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dob1 = sdf.format(Dob.getDate());
            String dept1 = DeptSec.getSelectedItem().toString();
            String state1 = State.getSelectedItem().toString();
            String address1 = Address.getText();
            String classSec1 = ClassSec.getSelectedItem().toString();
            String yoa1 = YearOfAdmission.getText();
            
            System.out.println(enrollmentId1);
            System.out.println(fullName1);
            System.out.println(dob1);
            
            
            String query = "select Dept_Id from department where Dept_code='" + dept1 + "'";
            PreparedStatement preparedStatement1 = myConn.prepareStatement(query);
            ResultSet resultSet1 = preparedStatement1.executeQuery();
            String deptid = "";

            while (resultSet1.next()) {
                deptid = resultSet1.getString("Dept_Id");
            }
            myConn.close();
            Connection con = MySQLConnection.getConnection();
            String query1="UPDATE student SET Password = '" + password1 + "', StudName = '" + fullName1 +
                    "', Gender = '" + gender1.substring(0, 1) + "', MobileNo = '" + contactNumber1
                    + "', email = '" + emailId1 + "', dob = '" + dob1 + "', DeptId = '" + deptid+ "', YearOfAdmission = '" + yoa1
                    + "', MotherName = '" + motherName1 + "', FatherName = '" + fatherName1 +
                    "', City = '" + city1 + "', State = '" + state1 + "', Address = '" + address1 + "',Class = '" + classSec1 + "' WHERE (EnrollmentId = '"+ enrollmentId1 + "')";

            
            PreparedStatement ps = con.prepareStatement(query1);
            //System.out.println(query1);
            
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Student updated Successfully!!");

        } catch (Exception exception) {
            JOptionPane.showMessageDialog(this, "Database error: " + exception.getMessage());
            //System.out.println(exception);
        }
    }//GEN-LAST:event_UpdatestudentbtnActionPerformed

    private void FullNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FullNameFocusGained
        // TODO add your handling code here:
        if (FullName.getText().equals("First Name")) {
            FullName.setText("");
            FullName.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_FullNameFocusGained

    private void FullNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FullNameFocusLost
        // TODO add your handling code here:
        if (FullName.getText().equals("")) {
            FullName.setText("First Name");
            FullName.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_FullNameFocusLost

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void MotherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MotherNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(E_updatestud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(E_updatestud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(E_updatestud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(E_updatestud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new E_updatestud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JTextField AcadmicYear;
    private static javax.swing.JTextArea Address;
    private static javax.swing.JTextField City;
    private static javax.swing.JComboBox<String> ClassSec;
    private static javax.swing.JTextField ContactNumber;
    private static javax.swing.JComboBox<String> DeptSec;
    private static com.toedter.calendar.JDateChooser Dob;
    private static javax.swing.JTextField EmailId;
    private static javax.swing.JTextField EnrollmentId;
    private static javax.swing.JTextField FatherName;
    private static javax.swing.JTextField FullName;
    private static javax.swing.JComboBox<String> Gender;
    private static javax.swing.JTextField MotherName;
    private static javax.swing.JTextField Password;
    private static javax.swing.JComboBox<String> State;
    private javax.swing.JButton Updatestudentbtn;
    private static javax.swing.JTextField YearOfAdmission;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}

class GetStudDeails {

    public static String password;
    public static String fullname;

    //String dept_code = resultSet.getString("Dept_Code");
    public static String gender;
    public static Long mobileno;
    public static String email;
    public static Date dob;
    public static String DeptCode;
    public static String yoa;
    //String dept_code = resultSet.getString("Dept_Code");

    public static String mothername;
    public static String fatherrname;
    public static String city;
    public static String state;
    public static String address;
    public static int adaceminid;
     public static int deptid;
    public static String studclass;

    public void getDataStud(String enroll) {

        try {

            Connection myConn = MySQLConnection.getConnection();

            String mySqlQuery
                    = "SELECT * from student where EnrollmentId=" + enroll;

            PreparedStatement preparedStatement = myConn.prepareStatement(mySqlQuery);
            //System.out.println(mySqlQuery);
            ResultSet resultSet = preparedStatement.executeQuery();

            while (resultSet.next()) {

                password = resultSet.getString("Password");
                fullname = resultSet.getString("StudName");                
                gender= resultSet.getString("Gender");
                mobileno = resultSet.getLong("MobileNo");
                email = resultSet.getString("email");
                dob = resultSet.getDate("dob");
                deptid = resultSet.getInt("DeptId");
                yoa = resultSet.getString("YearOfAdmission");
                
                mothername = resultSet.getString("MotherName");
                fatherrname = resultSet.getString("FatherName");
                city = resultSet.getString("City");
                state = resultSet.getString("State");
                address = resultSet.getString("Address");
                adaceminid = resultSet.getInt("AcademId");
                studclass = resultSet.getString("Class");

            }
            String queary="select Dept_code from department where Dept_Id =" + deptid;
            
            PreparedStatement preparedStatement1 = myConn.prepareStatement(queary);
            //System.out.println(mySqlQuery);
            ResultSet resultSet1 = preparedStatement1.executeQuery();

            while (resultSet1.next()) {

                DeptCode = resultSet1.getString("Dept_code");
            
            }          
                
           
          
        } catch (Exception exception) {
            //System.out.print(exception);
            JOptionPane.showMessageDialog(null, "Database error: " + exception.getMessage());
        }

    }

}
