/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ExamCell;

import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import test.MySQLConnection;

/**
 *
 * @author ikuna
 */
public class New_Register extends javax.swing.JFrame {

    /**
     * Creates new form New_Register
     */
    public static String path;
    public New_Register() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        jTable2.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD,12));
        jTable2.getTableHeader().setOpaque(false);
        jTable2.getTableHeader().setBackground(new Color(32,136,203));
        jTable2.getTableHeader().setForeground(new Color(255,255,255));
        jTable2.setRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        EnrollmentId = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        ContactNumber = new javax.swing.JTextField();
        Gender = new javax.swing.JComboBox<>();
        EmailId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Dob = new com.toedter.calendar.JDateChooser();
        DeptSec = new javax.swing.JComboBox<>();
        MotherName = new javax.swing.JTextField();
        FatherName = new javax.swing.JTextField();
        State = new javax.swing.JComboBox<>();
        City = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Address = new javax.swing.JTextArea();
        addstudentbtn = new javax.swing.JButton();
        FirstName = new javax.swing.JTextField();
        YearOfAdmission = new com.toedter.calendar.JYearChooser();
        jLabel4 = new javax.swing.JLabel();
        ClassSec = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        uploadbtn = new javax.swing.JButton();
        imagelbl = new javax.swing.JLabel();
        pathfield = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField10 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(460, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(19, 103, 149));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(250, 250, 250));
        jLabel1.setText("New Register");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jRadioButton1.setText("Fresher/Diploma");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jRadioButton2.setText("Import Data From Excel Sheet");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 140));

        jTabbedPane1.setBackground(new java.awt.Color(102, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(250, 250, 250));

        EnrollmentId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EnrollmentId.setText("EnrollmentId");
        EnrollmentId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EnrollmentIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EnrollmentIdFocusLost(evt);
            }
        });
        EnrollmentId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrollmentIdActionPerformed(evt);
            }
        });

        Password.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Password.setText("Password");
        Password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFocusLost(evt);
            }
        });

        LastName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        LastName.setText("Last Name");
        LastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LastNameFocusLost(evt);
            }
        });
        LastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameActionPerformed(evt);
            }
        });

        ContactNumber.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ContactNumber.setText("Contact Number");
        ContactNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ContactNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ContactNumberFocusLost(evt);
            }
        });
        ContactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactNumberActionPerformed(evt);
            }
        });

        Gender.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        Gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderActionPerformed(evt);
            }
        });

        EmailId.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EmailId.setText("Email Id");
        EmailId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmailIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmailIdFocusLost(evt);
            }
        });
        EmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailIdActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setText("Date Of Birth :");

        DeptSec.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DeptSec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSE", "IT", "ENTC", "CIVIL", "ELN", "MECH", "MTECH" }));
        DeptSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeptSecActionPerformed(evt);
            }
        });

        MotherName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MotherName.setText("Mother Name");
        MotherName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MotherNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MotherNameFocusLost(evt);
            }
        });

        FatherName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FatherName.setText("Father Name");
        FatherName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FatherNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FatherNameFocusLost(evt);
            }
        });
        FatherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FatherNameActionPerformed(evt);
            }
        });

        State.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        State.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Andhra Pradesh", "Assam", "Arunachal Pradesh", "Bihar", "Goa", "Gujarat", "Jammu and Kashmir", "Jharkhand", "West Bengal", "Karnataka", "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Orissa", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Tripura", "Uttaranchal", "Uttar Pradesh", "Haryana", "Himachal Pradesh", "Chhattisgarh" }));

        City.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        City.setText("City");
        City.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CityFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Address :");

        Address.setColumns(20);
        Address.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Address.setRows(2);
        jScrollPane1.setViewportView(Address);

        addstudentbtn.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        addstudentbtn.setText("Add Student");
        addstudentbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudentbtnActionPerformed(evt);
            }
        });

        FirstName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        FirstName.setText("First Name");
        FirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FirstNameFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setText("Year Of Addmission");

        ClassSec.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ClassSec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FY-01", "FY-02", "SY-03", "SY-04", "TY-05", "TY-06", "BE-07", "BE-08" }));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(250, 250, 250));
        jLabel5.setText("Class:");

        uploadbtn.setBackground(new java.awt.Color(250, 250, 250));
        uploadbtn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        uploadbtn.setText("Upload");
        uploadbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadbtnActionPerformed(evt);
            }
        });

        imagelbl.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        imagelbl.setText("Image");
        imagelbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pathfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pathfield.setText("Selected Path");
        pathfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(EmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Dob, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MotherName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(State, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(DeptSec, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(YearOfAdmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addstudentbtn)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(imagelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(uploadbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pathfield, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EnrollmentId, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(103, 103, 103)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ClassSec, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(14, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnrollmentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(EmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DeptSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addComponent(YearOfAdmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MotherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(State, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClassSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(pathfield, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(uploadbtn)))
                .addGap(12, 12, 12)
                .addComponent(addstudentbtn)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Fresher", jPanel3);

        jButton2.setText("Import");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setAlignmentX(5.0F);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "EnrollmentId", "Password", "Name", "Gender", "Mobile No", "Email Id", "DOB", "deptID", "year of Adm", "Mother Name", "Father Name", "City", "State", "Address", "Class"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable2.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable2.setRowHeight(25);
        jTable2.setSelectionBackground(new java.awt.Color(232, 57, 95));
        jTable2.setShowVerticalLines(false);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(0).setHeaderValue("EnrollmentId");
            jTable2.getColumnModel().getColumn(1).setHeaderValue("Password");
            jTable2.getColumnModel().getColumn(2).setHeaderValue("Name");
            jTable2.getColumnModel().getColumn(3).setHeaderValue("Gender");
            jTable2.getColumnModel().getColumn(4).setHeaderValue("Mobile No");
            jTable2.getColumnModel().getColumn(5).setHeaderValue("Email Id");
            jTable2.getColumnModel().getColumn(6).setHeaderValue("DOB");
            jTable2.getColumnModel().getColumn(7).setHeaderValue("deptID");
            jTable2.getColumnModel().getColumn(8).setHeaderValue("year of Adm");
            jTable2.getColumnModel().getColumn(9).setHeaderValue("Mother Name");
            jTable2.getColumnModel().getColumn(10).setHeaderValue("Father Name");
            jTable2.getColumnModel().getColumn(11).setHeaderValue("City");
            jTable2.getColumnModel().getColumn(12).setHeaderValue("State");
            jTable2.getColumnModel().getColumn(13).setHeaderValue("Address");
            jTable2.getColumnModel().getColumn(14).setHeaderValue("Class");
        }

        jTextField10.setText("jTextField10");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton2)
                .addGap(68, 68, 68))
        );

        jTabbedPane1.addTab("Import", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 460, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public ImageIcon ResizeImage(String ImagePath, byte[] pic, javax.swing.JLabel name) {

        ImageIcon MyImage = null;
        if (ImagePath != null) {

            MyImage = new ImageIcon(ImagePath);
        } else {

            MyImage = new ImageIcon(pic);
        }
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(name.getWidth(), name.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    private void ContactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactNumberActionPerformed

    private void FatherNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FatherNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FatherNameActionPerformed

    private void EnrollmentIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrollmentIdActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_EnrollmentIdActionPerformed

    private void GenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderActionPerformed

    private void LastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameActionPerformed

    private void EmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailIdActionPerformed

    private void DeptSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeptSecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeptSecActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0); 
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1); 
    }//GEN-LAST:event_jRadioButton2ActionPerformed
    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser Chooser= new JFileChooser();
        Chooser.showOpenDialog(null);
        File f= Chooser.getSelectedFile();
        String filename=f.getAbsolutePath();
        jTextField10.setText(filename);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void EnrollmentIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EnrollmentIdFocusLost
        // TODO add your handling code here:
        if(EnrollmentId.getText().equals(""))
        {
           EnrollmentId.setText("EnrollmentId");
           EnrollmentId.setForeground(new Color(153,153,153));
        }
        
    }//GEN-LAST:event_EnrollmentIdFocusLost

    private void EnrollmentIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EnrollmentIdFocusGained
        // TODO add your handling code here:
        if(EnrollmentId.getText().equals("EnrollmentId"))
        {
           EnrollmentId.setText("");
           EnrollmentId.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_EnrollmentIdFocusGained

    private void PasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusGained
        // TODO add your handling code here:
        if(Password.getText().equals("Password"))
        {
           Password.setText("");
           Password.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_PasswordFocusGained

    private void PasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFocusLost
        // TODO add your handling code here:
        if(Password.getText().equals(""))
        {
           Password.setText("Password");
           Password.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_PasswordFocusLost

    private void FirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FirstNameFocusGained
        // TODO add your handling code here:
        if(FirstName.getText().equals("First Name"))
        {
           FirstName.setText("");
           FirstName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_FirstNameFocusGained

    private void FirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FirstNameFocusLost
        // TODO add your handling code here:
        if(FirstName.getText().equals(""))
        {
           FirstName.setText("First Name");
           FirstName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_FirstNameFocusLost

    private void LastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LastNameFocusGained
        // TODO add your handling code here:
        if(LastName.getText().equals("Last Name"))
        {
           LastName.setText("");
           LastName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_LastNameFocusGained

    private void LastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LastNameFocusLost
        // TODO add your handling code here:
        if(LastName.getText().equals(""))
        {
           LastName.setText("Last Name");
           LastName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_LastNameFocusLost

    private void ContactNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContactNumberFocusGained
        // TODO add your handling code here:
        if(ContactNumber.getText().equals("Contact Number"))
        {
           ContactNumber.setText("");
           ContactNumber.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_ContactNumberFocusGained

    private void ContactNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ContactNumberFocusLost
        // TODO add your handling code here:
        if(ContactNumber.getText().equals(""))
        {
           ContactNumber.setText("Contact Number");
           ContactNumber.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_ContactNumberFocusLost

    private void EmailIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailIdFocusGained
        // TODO add your handling code here:
        if(EmailId.getText().equals("Email Id"))
        {
           EmailId.setText("");
           EmailId.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_EmailIdFocusGained

    private void EmailIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmailIdFocusLost
        // TODO add your handling code here:
        if(EmailId.getText().equals(""))
        {
           EmailId.setText("Email Id");
           EmailId.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_EmailIdFocusLost

    private void MotherNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MotherNameFocusGained
        // TODO add your handling code here:
        if(MotherName.getText().equals("Mother Name"))
        {
           MotherName.setText("");
           MotherName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_MotherNameFocusGained

    private void MotherNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MotherNameFocusLost
        // TODO add your handling code here:
        if(MotherName.getText().equals(""))
        {
           MotherName.setText("Mother Name");
           MotherName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_MotherNameFocusLost

    private void FatherNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FatherNameFocusGained
        // TODO add your handling code here:
        if(FatherName.getText().equals("Father Name"))
        {
           FatherName.setText("");
           FatherName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_FatherNameFocusGained

    private void FatherNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FatherNameFocusLost
        // TODO add your handling code here:
        if(FatherName.getText().equals(""))
        {
           FatherName.setText("Father Name");
           FatherName.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_FatherNameFocusLost

    private void CityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CityFocusGained
        // TODO add your handling code here:
        if(City.getText().equals("City"))
        {
           City.setText("");
           City.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_CityFocusGained

    private void CityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CityFocusLost
        // TODO add your handling code here:
        if(City.getText().equals(""))
        {
           City.setText("City");
           City.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_CityFocusLost

    private void addstudentbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudentbtnActionPerformed
        // TODO add your handling code here:
        try {

            Connection myConn = MySQLConnection.getConnection();
            
            
            String enrollmentId=EnrollmentId.getText();
            String password=Password.getText();
            String firstName= FirstName.getText();
            String lastName= LastName.getText();
            String contactNumber= ContactNumber.getText();
            String emailId= EmailId.getText();
            String motherName= MotherName.getText();
            String fatherName=FatherName.getText();
            String city=City.getText();
            String gender = Gender.getSelectedItem().toString();
            
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); 
            String dob = sdf.format(Dob.getDate());
            
            String dept = DeptSec.getSelectedItem().toString();
            String state = State.getSelectedItem().toString();
            String address = Address.getText();
            String classSec = ClassSec.getSelectedItem().toString();
            int yoa = YearOfAdmission.getYear();
            //System.out.println(yoa);
            String name = lastName+" "+firstName;
            //System.out.println(name);
            
            String query="select Dept_Id from department where Dept_code='"+dept+"'";
            PreparedStatement preparedStatement1= myConn.prepareStatement(query);
            ResultSet resultSet1 = preparedStatement1.executeQuery();
            String deptid = "";

                while (resultSet1.next()) {
                  deptid = resultSet1.getString("Dept_Id");  
                }
            
            
            
            String query1 = "INSERT INTO student (EnrollmentId,Password,StudName,Gender,MobileNo,email,dob,DeptId,YearOfAdmission,MotherName,FatherName,City,State,Address,Class,images)"
                    + " values ("+enrollmentId+",'"+password+"','"+name+"','"+gender.substring(0,1)+"',"+contactNumber+
                    ",'"+emailId+"','"+dob+"',"+deptid+",'"+yoa+"','"+motherName+"','"+fatherName+"','"+city+"','"+state+"','"+address+"','"+classSec+"',?)";
            
            
            
            PreparedStatement preparedStatement = myConn.prepareStatement(query1);
            InputStream img = new FileInputStream(new File(path));
            preparedStatement.setBlob(1, img);
            
            
            
            //System.out.print(query1);
            preparedStatement.execute();
            JOptionPane.showMessageDialog(null, "Student Added Successfully!!");
            
 
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(this, "Database error: " + exception.getMessage());
            //System.out.println(exception);
        }
    }//GEN-LAST:event_addstudentbtnActionPerformed

    private void uploadbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadbtnActionPerformed
        // TODO add your handling code here:
        
        
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "*.jpg", "gif", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {

            File selectedFile = file.getSelectedFile();
            path = selectedFile.getAbsolutePath();
            pathfield.setText(path);
            imagelbl.setIcon(ResizeImage(path, null, imagelbl));

        } else{

            JOptionPane.showMessageDialog(null, "No new image selected");

        }
    }//GEN-LAST:event_uploadbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Address;
    private javax.swing.JTextField City;
    private javax.swing.JComboBox<String> ClassSec;
    private javax.swing.JTextField ContactNumber;
    private javax.swing.JComboBox<String> DeptSec;
    private com.toedter.calendar.JDateChooser Dob;
    private javax.swing.JTextField EmailId;
    private javax.swing.JTextField EnrollmentId;
    private javax.swing.JTextField FatherName;
    private javax.swing.JTextField FirstName;
    private javax.swing.JComboBox<String> Gender;
    private javax.swing.JTextField LastName;
    private javax.swing.JTextField MotherName;
    private javax.swing.JTextField Password;
    private javax.swing.JComboBox<String> State;
    private com.toedter.calendar.JYearChooser YearOfAdmission;
    private javax.swing.JButton addstudentbtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel imagelbl;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JLabel pathfield;
    private javax.swing.JButton uploadbtn;
    // End of variables declaration//GEN-END:variables
}
